### ISSUE TITLE
“AI 聊天+” 按钮意义不明

### ISSUE THREAD

**Issue by yuanye1010** [DirectionAI/DirectionAI-TestReport#12]
**Describe the bug**
“AI 聊天+” 按钮意义不明

**To Reproduce**
1. 首页边栏
2. 点击“AI 聊天+” 按钮，没有意义的跳转

**Expected behavior**
删除这个按钮或者进行有意义的跳转

**Screenshots**
![image](https://github.com/user-attachments/assets/5118fdf9-653e-4195-bdc5-63262e0199d7)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Microsoft Edge

**Comment by june805** [comment]
这个不是智能教学平台相关的功能，不用考虑
