### ISSUE TITLE
教师端-课程设置按钮点击无反应

### ISSUE THREAD

**Issue by yuanye1010** [DirectionAI/DirectionAI-TestReport#16]
**Describe the bug**
教师端-课程设置按钮点击无反应

**To Reproduce**
1. 教师端
2. 我的课程
3. 点击“设置”按钮
4. 无反应

**Expected behavior**
正确跳转

**Screenshots**
![image](https://github.com/user-attachments/assets/be60abfa-605e-4933-9ff2-be20cacc2e8b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge

**Comment by june805** [comment]
根据需求文档："设置按钮，暂时没有功能。为以后增加新的管理功能提供入口"。在后续的版本中再设计。
