### ISSUE TITLE
AI聊天无法记录历史聊天信息

### ISSUE THREAD

**Issue by Yijiu37** [DirectionAI/DirectionAI-TestReport#20]
**Describe the bug**
AI聊天处，发送聊天后，对方一直不响应（可能是我网络问题），且刷新后之前的聊天记录消失

**To Reproduce**
1. 点击AI MINDLLM聊天界面
2. 发送聊天信息
3. 刷新
4. 聊天信息消失

**Expected behavior**
刷新后保存之前的聊天信息

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Browser [edge]

**Comment by Yijiu37** [comment]
以及AI聊天自己这边应该显示自己的头像

**Comment by Yijiu37** [comment]
切换到学生端可以了！是不是游客端不能响应，也没有历史记录

**Comment by june805** [comment]
> 切换到学生端可以了！是不是游客端不能响应，也没有历史记录

是的，只有学生端才有这个功能，这不是一个真实的bug，先关掉。
