### ISSUE TITLE
视频播放点击上一篇下一篇无响应，且按钮和AI问答图标覆盖

### ISSUE THREAD

**Issue by Yijiu37** [DirectionAI/DirectionAI-TestReport#22]
**Describe the bug**
视频播放点击上一篇下一篇无响应

**To Reproduce**
1. 我的课程界面
2. 选择一门课程
3. 播放界面点击下一篇或上一篇无响应，且左侧菜单栏收起后，按钮与AI聊天图标覆盖

**Expected behavior**
点击下一篇和上一篇分别跳转到下一条视频和上一条视频
按钮与AI聊天图标不应该互相遮盖

**Screenshots**
![image](https://github.com/user-attachments/assets/b1557ab8-3182-402b-bc0f-8a765e5e230c)

**Comment by june805** [comment]
根据前端沟通，由于无法找到上一篇或者下一篇课程内容，需要隐藏按钮。
