### ISSUE TITLE
我的课程界面点击“首页”无反应

### ISSUE THREAD

**Issue by Yijiu37** [DirectionAI/DirectionAI-TestReport#25]
**Describe the bug**
我的课程界面点击“首页”无反应

**To Reproduce**
1. 登录或注册后，点击我的课程
2. 进入我的课程后，无法再次返回首页

**Expected behavior**
返回首页

**Screenshots**
![image](https://github.com/user-attachments/assets/e08b4588-c59a-4d4b-89e3-6ea638c1087e)

**Comment by Yijiu37** [comment]
以及个人这个地方没有显示个人头像？（感觉显示了更好看一些）
![image](https://github.com/user-attachments/assets/5a1e135d-599d-43f3-a389-c93e1de5cc39)

**Comment by june805** [comment]
解决方案： 去掉“首页”链接
