### ISSUE TITLE
学生端-开始作业按钮点击无响应

### ISSUE THREAD

**Issue by Yijiu37** [DirectionAI/DirectionAI-TestReport#28]
**Describe the bug**
点击某个课程，进入课程内部，右下角开始作业按钮点击无响应
以及拉动到这个章节最下方，布置的作业也无法进入

**Expected behavior**
希望在每一个章节顶端，提示：”本章节新增/包含X个作业，已完成...，未完成...“
点击开始作业之后，跳转该章节发布的对应的作业界面

**Screenshots**
![image](https://github.com/user-attachments/assets/c05a32fc-d0a8-4463-94d9-06df64f18b6c)

**Additional context**
作业和随堂测试区分开？比如作业是章节总测，随堂测试是每个章节下的几个小节的作业

**Comment by Yijiu37** [comment]
然后我这里”我的作业“一直加载不出来，学习历史也没有记录，不知道正不正常 :(

**Comment by june805** [comment]
@Yijiu37 应该是你账号下没有作业导致的。逻辑上应该是你没有被分配作业，不应该有“开始作业”选项。
已通知前端修改。
