### ISSUE TITLE
下一篇无反应

### ISSUE THREAD

**Issue by Gaoeve** [DirectionAI/DirectionAI-TestReport#9]
**Describe the bug**
点击下一篇无反应

**To Reproduce**
 

1.进入课程
2. 进入课程中的某一节课
3. 点击下一篇
4. 无反应

**Expected behavior**
点击下一篇后成功跳转
**Screenshots**
<img width="1342" alt="截屏2024-10-26 00 38 29" src="https://github.com/user-attachments/assets/0877a1b9-d65a-4a33-8e92-bcfeed81a224">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari

**Additional context**

**Comment by june805** [comment]
Duplicated with https://github.com/DirectionAI/DirectionAI-TestReport/issues/22, close this issue
